/**
 * All values for each match category
 */

// Activities
export const allActivities = [
  'Vulnerability assessment',
  'Adaptation planning',
  'Taking action',
  'Communicating and engaging',
  'Increasing investments in adaptation',
  'Changing policy and law',
  'Integrating equity',
]

// Hazards
export const allHazards = [
  'Air quality',
  'Changing seasons',
  'Drought',
  'Erosion and shoreline recession',
  'Extreme cold',
  'Extreme heat',
  'Flooding – coastal',
  'Flooding – general',
  'Flooding – rainfall-induced',
  'High winds',
  'Landslides',
  'Severe winter weather',
  'Shifting species, habitats, and ecosystems',
  'Vector-borne disease',
  'Water quality',
  'Wildfire',
]

// Community Size
export const allSizes = [
  'Under 5,000',
  '5,001–10,000',
  '10,001–50,000',
  '50,001–100,000',
  '100,001–200,000',
  '200,001–300,000',
  '300,001–400,000',
  '400,001–500,000',
]

// Sectors
export const allSectors = [
  'Agriculture & food',
  'Biodiversity & ecosystems',
  'Buildings & infrastructure',
  'Business & economy',
  'Emergency preparedness',
  'Energy',
  'Equity',
  'Fisheries & aquaculture',
  'Forestry',
  'Land use planning',
  'Policy',
  'Public health',
  'Tourism & recreation',
  'Transportation',
  'Water', 
]

// All US States and Territories
export const allStates = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'District of Columbia (DC)',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
  'American Samoa',
  'Guam',
  'Northern Mariana Islands',
  'Puerto Rico',
  'Virgin Islands'
];