export const practitionerFieldMap = {
  airtableRecId: 'org_airtable_record_id',
  state: 'org_states_territories',
  size: 'org_comm_size',
  activities: 'org_services_provided_other',
  sectors: 'org_sectors',
  hazards: 'org_climate_hazards',
  name: 'org_name',
  org: 'org_name',
  website: 'org_website',
  status: 'org_status',
  linkedIn: 'org_linkedin',
  email: 'org_contact_email',
  phone: 'org_contact_phone',
  strTrained: 'org_str',
  info: "org_description",
  organizationType: 'org_type',
  additionalInformation: 'org_description',
  specificTypesOfCommunities: 'org_comm_specialization',
  languageFluencies: 'org_languages',
  org_street: 'org_street',
  org_city: 'org_city',
  org_state: 'org_state',
  org_zip: 'org_zip',
  org_registry_category: 'org_registry_category',
  org_registry_category_specialist: 'org_registry_category_specialist',
  org_services_provided_top: 'org_services_provided_top',
  org_Registry_public: 'org_Registry_public',
  topServicesProvided: 'org_services_provided_top',
  org_contact_position: 'org_contact_position',
  org_adaptation_staff: 'org_adaptation_staff',
  adaptationYears: 'org_adaptation_years',
  org_addl_background_info: 'org_addl_background_info',
  org_app_created: 'org_app_created',
  org_app_modified: 'org_app_modified',
  org_app_notified_of_determination: 'org_app_notified_of_determination',
  org_app_reviews: 'org_app_reviews',
  org_engagement_approach: 'org_engagement_approach',
  org_equity_approach: 'org_equity_approach',
  org_languages_other_specify: 'org_languages_other_specify',
  org_other_approach_info: 'org_other_approach_info',
  sbaCategory: 'org_sba_category',
  org_trainings: 'org_trainings',
  org_trainings_name_year: 'org_trainings_name_year',
  org_uncertainty_approach: 'org_uncertainty_approach',
  org_unintended_consequences_approach: 'org_unintended_consequences_approach',
  surveymonkey_responseid: 'surveymonkey_responseid',
  termsAndConditions: 'terms_conditions',
  includeOnRegistry: 'org_Registry_public',

  example1_title: 'example1_title',
  example1_description: 'example1_description',
  example1_links: 'example1_links',
  example1_location: 'example1_location',
  example1_engagement: 'example1_engagement',
  example1_equity: 'example1_equity',

  example2_title: 'example2_title',
  example2_description: 'example2_description',
  example2_location: 'example2_location',
  example2_engagement: 'example2_engagement',
  example2_equity: 'example2_equity',
  example2_links: 'example2_links',

  example3_title: 'example3_title',
  example3_description: 'example3_description',
  example3_location: 'example3_location',
  example3_engagement: 'example3_engagement',
  example3_equity: 'example3_equity',
  example3_links: 'example3_links',
};

export const validServices = [
  'Adaptation planning',
  'Changing policy and law',
  'Communicating and engaging',
  'Financing resilience projects and programs',
  'Integrating equity',
  'Project implementation',
  'Vulnerability assessment',
];

export const validHazards = [
  'Extreme heat',
  'Changes in seasons',
  'Drought',
  'Extreme precipitation',
  'Sea level rise and coastal erosion',
  'Flooding',
  'Hurricanes and other storms',
  'Severe winter weather',
  'Shifting species/habitats/ecosystems',
  'Vector-borne disease',
  'Water quality',
  'Air quality',
  'Wildfire',
];

export const validSectors = [
  'Agriculture and food',
  'Biodiversity and ecosystems',
  'Buildings and infrastructure',
  'Business and economy',
  'Emergency preparedness',
  'Energy',
  'Equity',
  'Fisheries and aquaculture',
  'Forestry',
  'Land use planning',
  'Policy',
  'Public health',
  'Tourism and recreation',
  'Transportation',
  'Water',
];

export const validCommunitySize = [
  'Under 10k',
  '10k-50k',
  '50k-100k',
  '100k-200k',
  '200k-300k',
  '300k-400k',
  '400k-500k',
  'Over 500k',
];

export const validStates = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'District of Columbia (DC)',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
  'American Samoa',
  'Guam',
  'Northern Mariana Islands',
  'Puerto Rico',
  'Virgin Islands',
];
